---
# we can have text properties which specify what text to draw (think atlas, prelim, internal)
# NOTE indentation matters
#   # this one pulls in all of the reference that's pre-defined
#   texts:
#     - *atlas
#   # this one merges the &internal with the current hash so everything but the label is the same
#   texts:
#     - label: preliminary
#       <<: *internal
#   texts:
#     - x: <position>
#       y: <position>
#       font: <number> (for SetTextFont(...))
#       size: <number> (for SetTextSize(...))
#       label: <string> (what to actually say)
atlas: &atlas
  x: 0.225
  y: 0.88
  font: 73
  size: 25
  label: ATLAS

internal: &internal
  x: 0.35
  font: 43
  label: Internal
  <<: *atlas

atlasinternal: &atlasinternal
  - *atlas
  - *internal

# top level defines the label / grouping
# second level is a list of files under that group, one can also specify a wildcard to match files so they all get grouped
# third level specifies extra information for a given file such as plots to ignore
# groups:
#   - name: <group name>
#     files:
#       - <a file path or a file pattern to match a set of files>
#     styles:
#       <name of style>: <value for style>
#   - name: <group name>
#     files: [file1, file2, ...]
#     styles: {style1: val1, style2: val2, ...}

# styles are set on all hists associated with that group
# styles:
#   - drawstyle (passed into Draw(...), think 'same' or 'hist')
#   - legendstyle (passed into Legend(...), think 'F')
#   - markercolor (also set with 'color')
#   - markerstyle
#   - markersize
#   - fillcolor (also set with 'color')
#   - fillstyle
#   - linecolor (also set with 'color')
#   - linestyle
#   - linewidth
#   - color (sets markercolor, fillcolor, linecolor)

groups:
  - name: &normalize "t#bar{t}"
    files:
      - /Users/kratsg/hists_HFSF2015/fetch/*410000*
    styles:
      legendstyle: L
      drawstyle: hist
      linewidth: 2
    stack it: false

#  - name: "Z' (2250)"
#    files:
#      - /Users/kratsg/hists_HFSF2015/fetch/*301330*
#    styles:
#      legendstyle: L
#      drawstyle: hist
#      linewidth: 2
#    stack it: false
#
#  - name: "Z' (2750)"
#    files:
#      - /Users/kratsg/hists_HFSF2015/fetch/*301332*
#    styles:
#      legendstyle: L
#      drawstyle: hist
#      linewidth: 2
#    stack it: false

  - name: "dijet (4W-8W)"
    files:
      - /Users/kratsg/hists_HFSF2015/fetch/*361024*
      - /Users/kratsg/hists_HFSF2015/fetch/*361025*
      - /Users/kratsg/hists_HFSF2015/fetch/*361026*
      - /Users/kratsg/hists_HFSF2015/fetch/*361027*
      - /Users/kratsg/hists_HFSF2015/fetch/*361028*
    styles:
      legendstyle: F
      fillstyle: solid
    stack it: true

# plots:
#   config:  # here we set global configurations that are applied uniformly such as...
#     canvas:
#     legend:
#     texts:

defaultTexts:
  - &topline
    x: 0.25
    y: 0.84
    font: 43
    size: 18
    label: "#sqrt{s} = 13 TeV, L_{int} = 1.00 fb^{-1}"

  - &preselectionText
    y: 0.80
    font: 43
    size: 18
    label: "p_{T}^{jet} #geq 450 GeV"
    <<: *topline

plots:
  config:
    normalize: *normalize
    texts:
      - *atlas
      - *internal
    canvas:
      width: 650
      height: 500
      logy: false
      ndivisions: 505
    legend:
      leftmargin: 0.425
      topmargin: 0.025
      rightmargin: 0.075
      textsize: 14
      entrysep: 0.01
      entryheight: 0.02

  paths:
    originCorrection/cluster_centerMag:
      ylabel: "clusters"
      xlabel: "cluster center magnitude"
      texts: [*preselectionText]
    originCorrection/vxp_z:
      ylabel: "events"
      xlabel: "primary vertex z_{0}"
      texts: [*preselectionText]
